<a href="https://colab.research.google.com/github/kimchaeyoung-student/Graduation/blob/main/DentalCare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#드라이브에 접근할 수 있도록 아래 코드 입력
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [31]:
#불러올 파일의 경로를 filename 변수에 저장
filename = '/content/drive/My Drive/hospital.csv'
filename2 = '/content/drive/My Drive/subway.csv'

In [16]:
import pandas as pd

In [17]:
#pandas read_csv로 불러오기
data = pd.read_csv(filename)
data.head()

   번호 개방서비스명     개방서비스id  개방자치단체코드  ... 총인원  구조사수  허가병상수  최초지정일자
0   1     병원  01_01_01_P   6460000  ... NaN   NaN    0.0     NaN
1   2     병원  01_01_01_P   3120000  ... NaN   NaN    0.0     NaN
2   3     병원  01_01_01_P   3190000  ... NaN   NaN    0.0     NaN
3   4     병원  01_01_01_P   4020000  ... NaN   NaN    0.0     NaN
4   5     병원  01_01_01_P   4010000  ... NaN   NaN    0.0     NaN

[5 rows x 44 columns]

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6507 entries, 0 to 6506
Data columns (total 44 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   번호         6507 non-null   int64
 1   개방서비스명     6507 non-null   object
 2   개방서비스id    6507 non-null   object
 3   개방자치단체코드   6507 non-null   int64
 4   관리번호       6507 non-null   object
 5   인허가일자      6507 non-null   int64
 6   인허가취소일자    1 non-null      float64
 7   영업상태구분코드   6507 non-null   int64
 8   영업상태명      6507 non-null   object
 9   상세영업상태코드   6507 non-null   object
 10  상세영업상태명    6506 non-null   object
 11  폐업일자       2011 non-null   float64
 12  휴업시작일자     239 non-null    float64
 13  휴업종료일자     235 non-null    float64
 14  재개업일자      0 non-null      float64
 15  소재지전화      6243 non-null   object
 16  소재지면적      0 non-null      float64
 17  소재지우편번호    2874 non-null   object
 18  소재지전체주소    5287 non-null   object
 19  도로명전체주소    6161 non-null   object
 20  도로명우편번호    5434 non-null   float64
 21  사업장명       6507 non-null   object
 22  최종수정시점     6507 non-null   float64
 23  데이터갱신구분    6507 non-null   object
 24  데이터갱신일자    6507 non-null   object
 25  업태구분명      6507 non-null   object
 26  좌표정보(x)    5957 non-null   float64
 27  좌표정보(y)    5957 non-null   float64
 28  의료기관종별명    6333 non-null   object
 29  의료인수       6430 non-null   float64
 30  입원실수       6432 non-null   float64
 31  병상수        6432 non-null   float64
 32  총면적        6379 non-null   float64
 33  진료과목내용     6173 non-null   object
 34  진료과목내용명    6173 non-null   object
 35  지정취소일자     0 non-null      float64
 36  완화의료지정형태   0 non-null      float64
 37  완화의료담당부서명  0 non-null      float64
 38  구급차특수      6434 non-null   float64
 39  구급차일반      6434 non-null   float64
 40  총인원        0 non-null      float64
 41  구조사수       0 non-null      float64
 42  허가병상수      6434 non-null   float64
 43  최초지정일자     0 non-null      float64
dtypes: float64(23), int64(4), object(17)
memory usage: 2.2+ MB

In [19]:
dental = data[data["업태구분명"]=="치과병원"]

In [20]:
# Save iot data in csv file.
dental.to_csv('dental.csv')

In [21]:
import folium
from pandas import DataFrame   # 데이터 분석 패키지
from pandas import ExcelFile

In [24]:
dentalfile = '/content/dental.csv'  # 치과병원만 뽑아낸 파일

In [25]:
d = pd.read_csv(dentalfile)
d.head()

   Unnamed: 0   번호 개방서비스명     개방서비스id  ...  총인원 구조사수  허가병상수  최초지정일자
0          12   13     병원  01_01_01_P  ...  NaN  NaN    0.0     NaN
1          96   97     병원  01_01_01_P  ...  NaN  NaN    0.0     NaN
2          97   98     병원  01_01_01_P  ...  NaN  NaN    0.0     NaN
3         107  108     병원  01_01_01_P  ...  NaN  NaN    0.0     NaN
4         117  118     병원  01_01_01_P  ...  NaN  NaN    0.0     NaN

[5 rows x 45 columns]

In [26]:
df = dental.filter(['사업장명''업태구분명','도로명전체주소','좌표정보(x)','좌표정보(y)'])
df

                    사업장명 업태구분명  ...      좌표정보(x)      좌표정보(y)
12                을지치과병원  치과병원  ...  199213.9958  451479.2513
96               참조은치과병원  치과병원  ...  192429.1403  455926.6494
97                성가치과병원  치과병원  ...  192443.7067  456716.7031
107               한양치과병원  치과병원  ...  194251.3636  455531.0132
117               송파치과병원  치과병원  ...  208426.1691  444447.6822
...                  ...   ...  ...          ...          ...
6367           서울귀한이치과병원  치과병원  ...  200800.4170  444989.8743
6370               필치과병원  치과병원  ...  198946.3256  443620.4529
6376             서울탑치과병원  치과병원  ...  201322.3049  442566.6411
6426            에이라인치과병원  치과병원  ...  238290.8572  347204.2411
6474  의료법인 이손의료재단 이손치과병원  치과병원  ...  167065.3569  377371.4508

[337 rows x 5 columns]

In [27]:
df2 = df['도로명전체주소'].str.contains('서울특별시')
df2

12       True
96       True
97       True
107      True
117      True
        ...
6367     True
6370     True
6376     True
6426    False
6474    False
Name: 도로명전체주소, Length: 337, dtype: object

In [ ]:
for i in df2.index:
  lat = df2.loc[i,'좌표정보(x)']
  lng = df2.loc[i,'좌표정보(y)']

  marker = folium.Marker([lat,lng], popup=name)
  marker.add_to(map_osm)

map_osm.save('서울의_치과병원분포.html')
map_osm

-----

In [32]:
subway = pd.read_csv(filename2)

In [33]:
subway

         지하철역명         위도          경도
0         가락시장  37.492522  127.118234
1         종로3가  37.571607  126.991806
2           오금  37.502162  127.128111
3          동대문  37.571420  127.009745
4    동대문역사문화공원  37.565138  127.007896
..         ...        ...         ...
584         동백  37.269043  127.152716
585         초당  37.260752  127.159443
586         삼가  37.242115  127.168075
587     시청·용인대  37.239151  127.178406
588        명지대  37.237964  127.190294

[589 rows x 3 columns]

In [34]:
map_osm = folium.Map(location=[37.566647,126.978426], zoom_start=10, tiles='Stamen Terrain')
map_osm

In [ ]:

for i in df3.index:
    # 행 우선 접근 방식으로 값 추출하기
    name = df3.loc[i, '지하철역명']
    lat = df3.loc[i, '위도']
    lng = df3.loc[i, '경도']
    
    # 추출한 정보를 지도에 표시
    marker = folium.Marker([lat,lng], popup=name)
    marker.add_to(map_osm)

map_osm.save('서울의_지하철역_분포.html')
map_osm